# Generated by Django 4.2 on 2023-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=200)),
                ('cafe_wifi', models.BooleanField(default=False)),
                ('cafe_address', models.CharField(default='N/A', max_length=1000)),
                ('cafe_rating', models.CharField(default='NIL', max_length=5)),
            ],
        ),
    ]
